### ISSUE TITLE
How to add textblock and barcode in it ?

### ISSUE THREAD

**Issue by SniperChan** [gerardo-lijs/DesignerCanvas#1]
This project is very useful for me, thanks a lot. How to add textblock and barcode in it ? Can you give an example?

**Comment by gerardo-lijs** [comment]
Hi, glad you found this useful. You can add almost anything inside a DesignerItem. For TextBlock for example it would be something like this:

```xml
<lijsdev:DesignerItem
    Canvas.Left="200"
    Canvas.Top="10"
    Width="150"
    Height="150"
    Margin="50"
    Background="White">
    <TextBlock IsHitTestVisible="False" Text="Testing texblock" />
</lijsdev:DesignerItem>
```

And the result:
![image](https://user-images.githubusercontent.com/14139570/169657115-e9e329eb-5867-4b19-b507-d329ebb61345.png)

For Barcode it should also work, either with a Barcode image or a Barcode control.

**Comment by SniperChan** [comment]
It works,Thank you very much!
